import { Rocket } from 'lucide-react';

export default function Footer() {
  return (
    <footer className="border-t border-surface-800/50 bg-surface-950">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <div className="grid grid-cols-1 md:grid-cols-4 gap-8">
          <div className="col-span-1 md:col-span-2">
            <div className="flex items-center gap-2.5 mb-3">
              <div className="p-1.5 rounded-lg bg-gradient-to-br from-brand-600 to-frost">
                <Rocket size={16} className="text-white" />
              </div>
              <span className="text-base font-bold text-surface-50">StartupLaunch AI</span>
            </div>
            <p className="text-sm text-surface-400 max-w-md">
              Multi-agent AI platform that validates startup ideas in minutes. Get market analysis, competitor intel, and a pitch-ready report — all generated by specialized AI agents.
            </p>
          </div>
          <div>
            <h3 className="text-sm font-semibold text-surface-200 mb-3">Product</h3>
            <div className="space-y-2">
              <a href="/generate" className="block text-sm text-surface-400 hover:text-surface-200 transition-colors">Generate</a>
              <a href="/dashboard" className="block text-sm text-surface-400 hover:text-surface-200 transition-colors">Dashboard</a>
              <a href="/history" className="block text-sm text-surface-400 hover:text-surface-200 transition-colors">History</a>
            </div>
          </div>
          <div>
            <h3 className="text-sm font-semibold text-surface-200 mb-3">Company</h3>
            <div className="space-y-2">
              <a href="#" className="block text-sm text-surface-400 hover:text-surface-200 transition-colors">About</a>
              <a href="#" className="block text-sm text-surface-400 hover:text-surface-200 transition-colors">Privacy</a>
              <a href="#" className="block text-sm text-surface-400 hover:text-surface-200 transition-colors">Terms</a>
            </div>
          </div>
        </div>
        <div className="mt-8 pt-8 border-t border-surface-800/50 flex flex-col sm:flex-row items-center justify-between gap-4">
          <p className="text-xs text-surface-500">© 2026 StartupLaunch AI. All rights reserved.</p>
          <div className="flex items-center gap-4">
              <a href="#" className="text-surface-500 hover:text-surface-300 transition-colors"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M12 2C6.477 2 2 6.477 2 12c0 4.42 2.865 8.17 6.839 9.49.5.092.682-.217.682-.482 0-.237-.008-.866-.013-1.7-2.782.604-3.369-1.34-3.369-1.34-.454-1.156-1.11-1.462-1.11-1.462-.908-.62.069-.608.069-.608 1.003.07 1.531 1.03 1.531 1.03.892 1.529 2.341 1.087 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.11-4.555-4.943 0-1.091.39-1.984 1.029-2.683-.103-.253-.446-1.27.098-2.647 0 0 .84-.269 2.75 1.025A9.578 9.578 0 0112 6.836c.85.004 1.705.115 2.504.337 1.909-1.294 2.747-1.025 2.747-1.025.546 1.377.203 2.394.1 2.647.64.699 1.028 1.592 1.028 2.683 0 3.842-2.339 4.687-4.566 4.935.359.309.678.919.678 1.852 0 1.336-.012 2.415-.012 2.743 0 .267.18.578.688.48C19.138 20.167 22 16.418 22 12c0-5.523-4.477-10-10-10z"/></svg></a>
              <a href="#" className="text-surface-500 hover:text-surface-300 transition-colors"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z"/></svg></a>
          </div>
        </div>
      </div>
    </footer>
  );
}
