import { useState, useEffect } from 'react';
import { useParams } from 'react-router-dom';
import { motion } from 'framer-motion';
import { Download, TrendingUp, Swords, Palette, DollarSign, Megaphone, Presentation, CheckCircle2, AlertTriangle, Lightbulb, BarChart3, Target, Users } from 'lucide-react';
import Card from '../components/ui/Card';
import Tabs from '../components/ui/Tabs';
import Button from '../components/ui/Button';
import Badge from '../components/ui/Badge';
import Skeleton from '../components/ui/Skeleton';
import CompetitorBar from '../components/charts/CompetitorBar';
import ReportSection from '../components/report/ReportSection';
import { startupApi } from '../services/api';
import { useToast } from '../components/ui/Toast';
import { dummyReport } from '../data/dummyData';

const tabs = ['Overview', 'Market', 'Competitors', 'Branding', 'Revenue', 'Marketing', 'Pitch'];

const tabIcons = {
  Overview: CheckCircle2,
  Market: TrendingUp,
  Competitors: Swords,
  Branding: Palette,
  Revenue: DollarSign,
  Marketing: Megaphone,
  Pitch: Presentation,
};

export default function Report() {
  const { id } = useParams();
  const addToast = useToast();
  const [report, setReport] = useState(null);
  const [loading, setLoading] = useState(true);
  const [activeTab, setActiveTab] = useState('Overview');

  useEffect(() => {
    async function load() {
      try {
        const data = await startupApi.getReport(id);
        setReport(data);
      } catch {
        addToast('Failed to load report', 'error');
      } finally {
        setLoading(false);
      }
    }
    load();
  }, [id]);

  if (loading) {
    return (
      <div className="min-h-screen pt-8 pb-20">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 space-y-6">
          <Skeleton className="h-12 w-64" />
          <Skeleton className="h-10 w-full" />
          <Skeleton className="h-80 w-full" />
        </div>
      </div>
    );
  }

  const data = report || dummyReport;

  return (
    <div className="min-h-screen pt-8 pb-20">
      <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 mb-8"
        >
          <div>
            <div className="flex items-center gap-3 mb-1">
              <h1 className="text-2xl sm:text-3xl font-bold text-surface-50">Validation Report</h1>
              <Badge color={data.summary.verdict === 'Strong Go' ? 'green' : 'amber'}>
                {data.summary.verdict}
              </Badge>
            </div>
            <p className="text-surface-400">
              Comprehensive analysis generated by 7 specialized AI agents
            </p>
          </div>
          <Button variant="secondary" size="sm" icon={Download}>
            Export PDF
          </Button>
        </motion.div>

        {/* Tabs */}
        <Tabs tabs={tabs} activeTab={activeTab} onChange={setActiveTab} className="mb-8 overflow-x-auto" />

        {/* Tab Content */}
        {activeTab === 'Overview' && (
          <div className="space-y-6">
            <ReportSection title="Executive Summary" icon={CheckCircle2}>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div>
                  <h4 className="text-sm font-medium text-surface-400 mb-2">Strengths</h4>
                  <div className="space-y-2">
                    {data.summary.strengths.map((s, i) => (
                      <div key={i} className="flex items-center gap-2 text-sm text-surface-200">
                        <div className="w-1.5 h-1.5 rounded-full bg-emerald-400" />
                        {s}
                      </div>
                    ))}
                  </div>
                </div>
                <div>
                  <h4 className="text-sm font-medium text-surface-400 mb-2">Risks</h4>
                  <div className="space-y-2">
                    {data.summary.risks.map((r, i) => (
                      <div key={i} className="flex items-center gap-2 text-sm text-surface-200">
                        <div className="w-1.5 h-1.5 rounded-full bg-amber-400" />
                        {r}
                      </div>
                    ))}
                  </div>
                </div>
              </div>
              <div className="mt-6 p-4 rounded-xl bg-brand-500/5 border border-brand-500/10">
                <p className="text-sm text-surface-300 italic">
                  "{data.summary.oneLiner}"
                </p>
              </div>
            </ReportSection>
          </div>
        )}

        {activeTab === 'Market' && (
          <ReportSection title="Market Analysis" icon={TrendingUp}>
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-6">
              <Card className="text-center p-4">
                <p className="text-2xl font-bold text-surface-50">{data.market.tam}</p>
                <p className="text-xs text-surface-400">Total Addressable Market</p>
              </Card>
              <Card className="text-center p-4">
                <p className="text-2xl font-bold text-surface-50">{data.market.sam}</p>
                <p className="text-xs text-surface-400">Serviceable Available Market</p>
              </Card>
              <Card className="text-center p-4">
                <p className="text-2xl font-bold text-surface-50">{data.market.som}</p>
                <p className="text-xs text-surface-400">Serviceable Obtainable Market</p>
              </Card>
            </div>
            <div className="space-y-4">
              <div className="flex items-center gap-2">
                <TrendingUp size={16} className="text-emerald-400" />
                <span className="text-sm text-surface-200">Growth Rate: <strong className="text-emerald-400">{data.market.growthRate}</strong></span>
              </div>
              <p className="text-sm text-surface-300 leading-relaxed">{data.market.trend}</p>
              <div>
                <h4 className="text-sm font-medium text-surface-400 mb-2">Key Competitors</h4>
                <div className="flex flex-wrap gap-2">
                  {data.market.competitors.map(c => (
                    <Badge key={c} color="violet">{c}</Badge>
                  ))}
                </div>
              </div>
              <div className="p-4 rounded-xl bg-brand-500/5 border border-brand-500/10">
                <p className="text-sm text-surface-300">
                  <strong className="text-brand-400">Competitive Edge:</strong> {data.market.competitiveEdge}
                </p>
              </div>
            </div>
          </ReportSection>
        )}

        {activeTab === 'Competitors' && (
          <ReportSection title="Competitive Landscape" icon={Swords}>
            <div className="space-y-6">
              {data.competitors.map((c, i) => (
                <CompetitorBar
                  key={c.name}
                  {...c}
                  color={i === 0 ? '#ef4444' : i === 1 ? '#f59e0b' : '#6366f1'}
                />
              ))}
            </div>
          </ReportSection>
        )}

        {activeTab === 'Branding' && (
          <ReportSection title="Brand Strategy" icon={Palette}>
            <div className="space-y-6">
              <div className="flex items-center gap-4">
                <div className="p-4 rounded-xl bg-surface-800/50">
                  <p className="text-sm font-medium text-surface-50">{data.branding.name}</p>
                  <p className="text-xs text-surface-400 italic mt-1">"{data.branding.tagline}"</p>
                </div>
                <div className="flex gap-2">
                  {data.branding.colors.map(c => (
                    <div key={c} className="w-8 h-8 rounded-lg border border-surface-700" style={{ backgroundColor: c }} />
                  ))}
                </div>
              </div>
              <div>
                <h4 className="text-sm font-medium text-surface-400 mb-2">Recommended Tone</h4>
                <p className="text-sm text-surface-200">{data.branding.tone}</p>
              </div>
              <div className="space-y-2">
                {data.branding.suggestions.map((s, i) => (
                  <div key={i} className="flex items-start gap-2 text-sm text-surface-300">
                    <Lightbulb size={14} className="text-amber-400 mt-0.5 shrink-0" />
                    {s}
                  </div>
                ))}
              </div>
            </div>
          </ReportSection>
        )}

        {activeTab === 'Revenue' && (
          <ReportSection title="Revenue Model" icon={DollarSign}>
            <div className="space-y-6">
              <div className="grid grid-cols-2 sm:grid-cols-5 gap-4">
                {Object.entries(data.revenue.metrics).map(([key, val]) => (
                  <Card key={key} className="text-center p-3">
                    <p className="text-lg font-bold text-surface-50">{val}</p>
                    <p className="text-[10px] text-surface-400 uppercase tracking-wider">{key.replace(/([A-Z])/g, ' $1')}</p>
                  </Card>
                ))}
              </div>
              <div className="p-4 rounded-xl bg-surface-800/50">
                <p className="text-sm text-surface-300">
                  <strong className="text-surface-50">Model:</strong> {data.revenue.model}
                </p>
                <p className="text-sm text-surface-300 mt-1">
                  <strong className="text-surface-50">Pricing:</strong> {data.revenue.pricing}
                </p>
              </div>
            </div>
          </ReportSection>
        )}

        {activeTab === 'Marketing' && (
          <ReportSection title="Marketing Strategy" icon={Megaphone}>
            <div className="space-y-4">
              {data.marketing.map((m, i) => (
                <motion.div
                  key={m.channel}
                  initial={{ opacity: 0, x: -20 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ delay: i * 0.1 }}
                  className="flex items-center gap-4 p-4 rounded-xl bg-surface-800/30 border border-surface-800/50"
                >
                  <div className="flex-1">
                    <p className="text-sm font-medium text-surface-50">{m.channel}</p>
                    <p className="text-xs text-surface-400 mt-0.5">{m.expected}</p>
                  </div>
                  <div className="text-right">
                    <span className="text-sm font-bold text-brand-400">{m.budget}</span>
                    <p className="text-[10px] text-surface-500">of budget</p>
                  </div>
                </motion.div>
              ))}
            </div>
          </ReportSection>
        )}

        {activeTab === 'Pitch' && (
          <ReportSection title="Pitch Deck" icon={Presentation}>
            <div className="space-y-6">
              {Object.entries(data.pitch).map(([key, val], i) => (
                <motion.div
                  key={key}
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: i * 0.1 }}
                >
                  <h4 className="text-sm font-semibold text-brand-400 uppercase tracking-wider mb-1">
                    {key}
                  </h4>
                  <p className="text-sm text-surface-200 leading-relaxed">{val}</p>
                </motion.div>
              ))}
            </div>
          </ReportSection>
        )}
      </div>
    </div>
  );
}
