import Project from '../models/Project.js';
import Report from '../models/Report.js';

export async function exportPdf(req, res, next) {
  try {
    const { projectId } = req.body;

    if (!projectId) {
      return res.status(400).json({ error: 'projectId is required' });
    }

    const project = await Project.findById(projectId).lean();
    const report = await Report.findOne({ projectId }).lean();

    if (!project || !report) {
      return res.status(404).json({ error: 'Project or report not found' });
    }

    const reportText = generateReportText(project, report);

    res.setHeader('Content-Type', 'text/plain; charset=utf-8');
    res.setHeader('Content-Disposition', `attachment; filename="startup-report-${projectId}.txt"`);
    res.send(reportText);
  } catch (error) {
    next(error);
  }
}

function generateReportText(project, report) {
  const lines = [
    '='.repeat(60),
    '  STARTUP LAUNCH AI - VALIDATION REPORT',
    '='.repeat(60),
    '',
    `Project: ${project.idea.split(' ').slice(0, 2).join(' ')}`,
    `Idea: ${project.idea}`,
    `Industry: ${project.industry}`,
    `Country: ${project.country}`,
    `Score: ${project.score || 'N/A'}/100`,
    `Status: ${project.status}`,
    '',
    '-'.repeat(60),
    '  EXECUTIVE SUMMARY',
    '-'.repeat(60),
    `Verdict: ${report.summary?.verdict || 'N/A'}`,
    `One-Liner: ${report.summary?.oneLiner || 'N/A'}`,
    '',
    'Strengths:',
    ...(report.summary?.strengths || []).map((s) => `  + ${s}`),
    '',
    'Risks:',
    ...(report.summary?.risks || []).map((r) => `  - ${r}`),
    '',
    '-'.repeat(60),
    '  MARKET ANALYSIS',
    '-'.repeat(60),
    `TAM: ${report.market?.tam || 'N/A'}`,
    `SAM: ${report.market?.sam || 'N/A'}`,
    `SOM: ${report.market?.som || 'N/A'}`,
    `Growth Rate: ${report.market?.growthRate || 'N/A'}`,
    `Trend: ${report.market?.trend || 'N/A'}`,
    `Competitive Edge: ${report.market?.competitiveEdge || 'N/A'}`,
    '',
    '-'.repeat(60),
    '  COMPETITOR ANALYSIS',
    '-'.repeat(60),
    ...(report.competitors || []).map(
      (c) => `\n${c.name}\n  Funding: ${c.funding || 'N/A'}\n  Strength: ${c.strength || 0}/100\n  Weakness: ${c.weakness || 'N/A'}\n  Threat: ${c.threat || 'N/A'}`
    ),
    '',
    '-'.repeat(60),
    '  BRANDING',
    '-'.repeat(60),
    `Name: ${report.branding?.name || 'N/A'}`,
    `Tagline: ${report.branding?.tagline || 'N/A'}`,
    `Colors: ${(report.branding?.colors || []).join(', ')}`,
    `Tone: ${report.branding?.tone || 'N/A'}`,
    '',
    '-'.repeat(60),
    '  REVENUE MODEL',
    '-'.repeat(60),
    `Model: ${report.revenue?.model || 'N/A'}`,
    `Pricing: ${report.revenue?.pricing || 'N/A'}`,
    `ARR: ${report.revenue?.metrics?.arr || 'N/A'}`,
    `MRR: ${report.revenue?.metrics?.mrr || 'N/A'}`,
    `Gross Margin: ${report.revenue?.metrics?.grossMargin || 'N/A'}`,
    `LTV: ${report.revenue?.metrics?.ltv || 'N/A'}`,
    `CAC: ${report.revenue?.metrics?.cac || 'N/A'}`,
    `Payback Period: ${report.revenue?.metrics?.paybackPeriod || 'N/A'}`,
    '',
    'Projections:',
    ...(report.revenue?.projections || []).map(
      (p) => `  Year ${p.year}: ${p.revenue} (${p.customers} customers)`
    ),
    '',
    '-'.repeat(60),
    '  MARKETING STRATEGY',
    '-'.repeat(60),
    ...(report.marketing || []).map(
      (m) => `\n${m.channel}\n  Budget: ${m.budget}\n  Expected: ${m.expected || 'N/A'}`
    ),
    '',
    '-'.repeat(60),
    '  INVESTOR PITCH',
    '-'.repeat(60),
    `Problem: ${report.pitch?.problem || 'N/A'}`,
    `Solution: ${report.pitch?.solution || 'N/A'}`,
    `Market: ${report.pitch?.market || 'N/A'}`,
    `Traction: ${report.pitch?.traction || 'N/A'}`,
    `Team: ${report.pitch?.team || 'N/A'}`,
    `Ask: ${report.pitch?.ask || 'N/A'}`,
    '',
    '='.repeat(60),
    '  Generated by StartupLaunch AI',
    '='.repeat(60),
  ];

  return lines.join('\n');
}
